version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: cicd/Dockerfile.debian.optimized
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=info
      - PORT=8080
      - IP=0.0.0.0
    volumes:
      # Mount the database file for persistence (optional - image includes a copy)
      - ../source/main.db:/app/main.db
    restart: unless-stopped

  # Optional: Add a development service with hot reload
  web-dev:
    build:
      context: ..
      dockerfile: cicd/Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - ../source:/app
      - /app/target
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=debug
      - PORT=8080
      - IP=0.0.0.0
    profiles:
      - dev 