[application]

[web.app]
# HTML title tag content
title = "Nico Judge - Admin"
# Use custom HTML template
index_template = "assets/index.html"

# Server configuration for fullstack mode
[web.server]
# Enable server functions
server_fn = true
# Server port (optional, defaults to 8080)
port = 8080

# include `assets` in web platform
[web.resource]
# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
